@baseUrl = http://localhost:3000

### Create and Connect Instance
POST {{baseUrl}}/create-and-connect
Content-Type: application/json

{
  "instanceName": "testeapagar"
}

### Check Connection Status
GET {{baseUrl}}/connection-status/testeapagar

### Reconnect Instance
GET {{baseUrl}}/reconnect/gustavo

### Logout Instance
DELETE {{baseUrl}}/logout/teste2

### Send Messages
POST {{baseUrl}}/send-messages/teste2
Content-Type: application/json

{
  "contacts": [
    {
      "number": "5511974492361",
      "name": "John Doe"
    },
    {
      "number": "5511974492361",
      "name": "John Doe"
    }
  ],
  "messages": [
    "Hello %name%",
    "Vai se fude"
  ],
  "delay": 1000 
}
