@baseUrl = http://localhost:3000

### Create and Connect Instance
POST {{baseUrl}}/create-and-connect
Content-Type: application/json

{
  "instanceName": "gustavo"
}

### Check Connection Status
GET {{baseUrl}}/connection-status/gustavo

### Restart Instance
POST {{baseUrl}}/restart/gustavo

### Logout Instance
DELETE {{baseUrl}}/logout/gustavo









### Send Messages
POST {{baseUrl}}/send-messages/teste2
Content-Type: application/json

{
  "contacts": [
    {
      "number": "5511974492361",
      "name": "John Doe"
    },
    {
      "number": "5511974492361",
      "name": "Jane Smith"
    }
  ],
  "messages": [
    "Hello @name",
    "Vai se fude"
  ],
  "delay": 1000 //milessegundos
}

### Upload CSV and Send Messages
POST {{baseUrl}}/upload-csv-and-send/teste2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="contacts.csv"
Content-Type: text/csv

name,number
John Doe,5511974492361
Jane Smith,5511974492361
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="messages"

["Hello @name", "Oloco gordao"]
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="delay"

1000
------WebKitFormBoundary7MA4YWxkTrZu0gW--

